### ISSUE TITLE
Documentation on CLJ backend for an Electron app?

### ISSUE THREAD

**Issue by jefffriesen** [matthiasn/meo#11]
Thank you for this repo and the blog post. What's most interesting to me is how you have a Clojure backend within a Electron app. It doesn't sound like users have to set up a server running Clojure - this runs locally I thought. But Electron only has a node.js "backend". I looked through the code and the shell scripts and it wasn't obvious how you do this. Would you mind documenting what happens and how this is done? Thanks you

**Comment by matthiasn** [comment]
Sure. So initially I started meo (back then it was called iWasWhere) as a single page web application, with a Clojure backend. Then I discovered Electron and I really prefer the desktop application experience, over having meo open in one of potentially tens or hundreds of browser tabs.

I was then able to reuse the backend, fire up a packaged uberjar from the Electron app, and have the renderer process talk to it via websockets. The backend only listens to localhost, so I figured that's safe even on networks I don't necessarily trust.

The code for firing up the JVM process lives in `meo.electron.main.startup`. I've occasionally been thinking about moving everything over to the Electron/ClojureScript/Node side, but that's quite a bit of work, and the JVM of course has nice properties, like having futures so I can let longer running queries, e.g. for stats, run in a new thread. And the current setup has just been working pretty well.

Here's how the current architecture looks like:

![jvm-electron](https://user-images.githubusercontent.com/1390808/37568244-ca61f1dc-2ad2-11e8-9053-03b350bd4ecd.png)

I've marked the two sides of the Websocket connection. It is facilitated by [systems-toolbox-sente](https://github.com/matthiasn/systems-toolbox-sente). The communication between the electron main and renderer processes is facilitated by [systems-toolbox-electron](https://github.com/matthiasn/systems-toolbox-electron), which uses IPC instead of Websockets. It really is a drop-in replacement, as components need not know over which wires the communication takes place. 

Please let me know if you have further questions. I will also go into more detail in the next blog posts. Thanks

**Comment by jefffriesen** [comment]
This is really interesting. Thank you for explaining it. I never thought you could launch and uberjar from Electron and communicate over websockets. 

One interesting aspect of a Clojure backend instead of Clojurescript (Node) is doing complex, multi-core processing locally on the users machine. Not an application for Meo probably but it would be for me. 

Thanks again.
