### ISSUE TITLE
jumping width when creating new entry with timer

### ISSUE THREAD

**Issue by ChillkroeteTTS** [matthiasn/meo#2]
Hey,

Although it's just a minor issue, I noticed that the width of the editor box is jumping when I add a timer to an entry.
To reproduce:
- Create new Entry
- Add some text and task tag (probably irrelevant to the bug?)
- add and start the timer

I made a short video so you can reproduce it easier:
https://youtu.be/wYpqAEk-mvk

**Comment by matthiasn** [comment]
Hey, this should be fixed by moving the time into the footer and showing it in a 00:00:00 format. I never noticed this because I always save entries first before recording time on them. Just tested this usage in 0.4.173 and it looked fine. Closing this for now but please feel free to reopen if the issue persists. Cheers
